project_id = "rasajyltkwhqebcimrbi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.study-chat]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true
